spring.application.name=springSecurityJWT

spring.datasource.url = jdbc:postgresql://localhost:5432/krish
spring.datasource.username = postgres
spring.datasource.password = 2812

spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update

server.servlet.session.cookie.same-site = strict