spring.application.name=springSecurity

spring.security.user.name = krish
spring.security.user.password = 1234

server.servlet.session.cookie.same-site = strict

spring.datasource.url = jdbc:postgresql://localhost:5432/krish
spring.datasource.username = postgres
spring.datasource.password = 2812
